site_name: VultureOS Documentation
site_url: https://www.vultureproject.org/doc/
theme: readthedocs
extra_css:
- css/styling.css
plugins:
    - swagger-ui-tag
nav:
    - Home: index.md
    - Overview:
      - Packaging: overview/packaging.md
      - Deployment: overview/deploy.md
    - Global Config: 
      - Status Page: global_config/stats.md
      - Cluster settings: global_config/cluster.md
      - Nodes: global_config/node.md
      - Network Topology: global_config/network.md
      - TLS Settings: global_config/tls.md
      - PKI: global_config/pki.md
    - Services:
      - Frontend listeners: listener.md
    - Identity Providers: 
      - The repository concept: identity/repository.md
      - LDAP: identity/ldap.md
      - Kerberos: identity/kerberos.md
      - Radius: identity/radius.md
      - MFA & OTP: identity/mfa.md
      - Time-based OTP Profiles: identity/totp.md
      - OpenID Federation: identity/openid.md
      - User's Scope: identity/scopes.md
      - SSO Profiles: identity/sso_profiles.md
    - Authentication Portal:
      - Portal: portal/portal.md
    - Applications :
      - Applications: backend.md
    - API:
      - Swagger: api.md