site_name: VultureOS Documentation
site_url: https://www.vultureproject.org/doc/
theme: readthedocs
extra_css:
- css/styling.css
plugins:
    - swagger-ui-tag
nav:
    - Home: index.md
    - Overview:
      - Packaging: overview/packaging.md
      - Deployment: overview/deploy.md
      - Quick start: overview/quickstart.md
    - Global Config: 
      - Status Page: global_config/stats.md
      - Cluster settings: global_config/cluster.md
      - Nodes: global_config/node.md
      - Multi-Tenants: global_config/tenant.md
      - Network Interfaces: global_config/network.md
      - Users: global_config/users.md
      - X509 Certificates: global_config/pki.md
      - TLS Profiles: global_config/tls.md
    - Services:
      - Frontend listeners: services/listener.md
      - IPSEC Client: services/ipsec_client.md
      - VPNSSL Client: services/vpnssl_client.md
    - Identity Providers: 
      - The repository concept: identity/repository.md
      - LDAP: identity/ldap.md
      - Kerberos: identity/kerberos.md
      - Radius: identity/radius.md
      - MFA & OTP: identity/mfa.md
      - Time-based OTP Profiles: identity/totp.md
      - OpenID Federation: identity/openid.md
      - User's Scope: identity/scopes.md
      - SSO Profiles: identity/sso_profiles.md
    - Authentication Portal:
      - Portal: portal/portal.md
    - Applications :
      - Log Forwarders: applications/logs_forwarder.md
      - Backend servers: applications/backend.md
    - API:
      - Swagger: api.md